##### gtrl Config #####
---
##### DRL #####
SEED : 1  # Random seed number
DESC : 'im_03' # describe what are you dowing
MAX_STEPS : 2000 # 300
MAX_EPISODES : 10  # 500 Maximum number of steps to perform
BATCH_SIZE : 32  # Size of the mini-batch
LR_A : 0.001 # Actor learning rate
LR_C : 0.001 # Critic learning rate
GAMMA : 0.999  # Discount factor to calculate the discounted future reward (should be close to 1)
TAU : 0.005  # Soft target update variable (should be close to 0)
ACTOR_FREQ : 1  # Frequency of Actor network updates
BUFFER_SIZE : 30000  # 2e5 Maximum size of the buffer
FRAME_STACK : 4 # Number of Channel
PLOT_INTERVAL : 1
EVAL_THRESHOLD : 80 # episode trigger for evaluation
SAVE_THRESHOLD : 1 # episode trigger for saving the model
REWARD_THRESHOLD : 90 # reward trigger for evaluation
SAVE : True # whether to save the model or not

###### Attention #####
P_ATTENTION_FIX : False # whether fix the weights and bias of transformer
C_ATTENTION_FIX : False # # whether fix the weights and bias of transformer

###### Human Intervention #####
PRE_BUFFER : False # Human expert buffer

##### Entropy #####
AUTO_TUNE : True # whether automatically tune the temperature parameter
ALPHA : 1.0
LR_ALPHA : 0.0001

##### Environment #####
ENV_NAME : "RRC"
L_SCALE : 0.5
A_SCALE : 2

##### Algo ######

GoT-SAC:
    name : 'gtrl'
    actor_type : "GaussianTransformer"
    critic_type : "CNN" # CNN or Transformer
    block : 4
    head : 4